export const ESTADOS_BR = [
  { sigla: 'AC', nome: 'Acre' },
  { sigla: 'AL', nome: 'Alagoas' },
  { sigla: 'AP', nome: 'Amapá' },
  { sigla: 'AM', nome: 'Amazonas' },
  { sigla: 'BA', nome: 'Bahia' },
  { sigla: 'CE', nome: 'Ceará' },
  { sigla: 'DF', nome: 'Distrito Federal' },
  { sigla: 'ES', nome: 'Espírito Santo' },
  { sigla: 'GO', nome: 'Goiás' },
  { sigla: 'MA', nome: 'Maranhão' },
  { sigla: 'MT', nome: 'Mato Grosso' },
  { sigla: 'MS', nome: 'Mato Grosso do Sul' },
  { sigla: 'MG', nome: 'Minas Gerais' },
  { sigla: 'PA', nome: 'Pará' },
  { sigla: 'PB', nome: 'Paraíba' },
  { sigla: 'PR', nome: 'Paraná' },
  { sigla: 'PE', nome: 'Pernambuco' },
  { sigla: 'PI', nome: 'Piauí' },
  { sigla: 'RJ', nome: 'Rio de Janeiro' },
  { sigla: 'RN', nome: 'Rio Grande do Norte' },
  { sigla: 'RS', nome: 'Rio Grande do Sul' },
  { sigla: 'RO', nome: 'Rondônia' },
  { sigla: 'RR', nome: 'Roraima' },
  { sigla: 'SC', nome: 'Santa Catarina' },
  { sigla: 'SP', nome: 'São Paulo' },
  { sigla: 'SE', nome: 'Sergipe' },
  { sigla: 'TO', nome: 'Tocantins' },
];

export const STATUS_LABELS: Record<string, string> = {
  em_prospeccao: 'Em Prospecção',
  em_andamento: 'Em Andamento',
  ganho: 'Ganho',
  perdido: 'Perdido',
  pausado: 'Pausado',
};

export const TIPOS_SOLUCAO = [
  'Comunicação Aumentativa e Alternativa (CAA)',
  'Acessibilidade Física',
  'Tecnologia Assistiva para Mobilidade',
  'Software de Acessibilidade',
  'Adaptações para Deficiência Visual',
  'Adaptações para Deficiência Auditiva',
  'Equipamentos para Reabilitação',
  'Outro',
];

export const CATEGORIAS_KIT = [
  'Biblioteca',
  'Sala de Recursos',
  'Laboratório de Informática',
  'Comunicação Alternativa',
  'Mobilidade',
  'Reabilitação',
  'Deficiência Visual',
  'Deficiência Auditiva',
  'Outro',
];
